name: Docker Build and Push with Build Args Injection

on: 
  push: 
    paths:
      - '.github/workflows/v2.0.0-advanced.yml'

jobs:
  docker-login-build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, Tag & Publish Image to DockerHub with Advanced options
        uses: dinushchathurya/build-tag-push-action@v2.0.0-rc.1
        with:
            username: ${{ secrets.DOCKER_NEW_USERNAME }}
            password: ${{ secrets.DOCKER_NEW_PASSWORD }}
            context: .
            file: Dockerfile  # Uses the modified Dockerfile
            repoOwner: ${{ secrets.DOCKER_NEW_USERNAME }}
            repository: build-push-tag-action
            tag: ${{ github.sha }}
            target: production
            network: host
            no_cache: false
            pull: true
            load: false
            cgroup_parent: /docker/test-container
            allow: network.host,security.insecure
            shm_size: 2g
            ulimit: |
              nofile=1024:1024
              nproc=2048:4096
              memlock=-1:-1
            add_hosts: |
              host.docker.internal:host-gateway
              custom.local:127.0.0.1
              api.internal:10.0.0.1
              db.internal:10.0.0.2

            
              