on: 
  push: 
    paths:
      - '.github/workflows/v2.0.0.yml'


jobs:
  docker-login-build-tag-push:
    runs-on: ubuntu-latest
    name: Docker Login, Build, Tag & Push to DockerHub
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v2.0.0-rc.1
        with:
          username: ${{ secrets.DOCKER_NEW_USERNAME }}
          password: ${{ secrets.DOCKER_NEW_PASSWORD }}
          context: .
          file: Dockerfile
          repoOwner: ${{ secrets.DOCKER_NEW_USERNAME }}
          repository:  build-push-tag-action
          tag: 1.0.0
          platforms: linux/amd64,linux/arm64  
    
       # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: dinushchathurya/build-tag-push-action@v2.0.0-rc.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
          context: .
          file: Dockerfile
          repoOwner: ${{ github.actor }}
          repository:  build-push-tag-action
          tag: nodejs-github
          platforms: linux/amd64,linux/arm64  


