on: [push]

jobs:
  docker-login-build-tag-push:
    runs-on: ubuntu-latest
    name: Docker Login, Build, Tag & Push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v2.0.0-rc.1
        with:
          username: ${{ secrets.DOCKER_NEW_USERNAME }}
          password: ${{ secrets.DOCKER__NEW_PASSWORD }}
          context: .
          file: Dockerfile
          repoOwner: ${{ secrets.DOCKER_NEW_USERNAME }}
          repository:  build-push-tag-action
          tag: 1.0.0
          push: true
          dry_run: false


